apiVersion: apps/v1
kind: Deployment
metadata:
  name: Contosoapp
  labels:
    app: Contosoapp
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1723072386336
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Contosoapp
  template:
    metadata:
      labels:
        app: Contosoapp
    spec:
      containers:
        - name: Contosoapp
          image: acrworkflow1723072386336.azurecr.io/image-workflow-1723072386336:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
